name: Profile Summary Cards

on:
  schedule:
    - cron: "0 3 * * *" # atualiza todo dia ~00:00 BRT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards-action@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Cintia-Olibar
          THEME: dracula
          BRANCH_NAME: main   # onde salvar os SVGs
